export const actionTypes = {
  SET_SESSION: 'SET-SESSION',

  SIGN_UP_START: 'SIGNUP-START',
  SIGN_UP_SUCCESS: 'SIGNUP-SUCCESS',
  SIGN_UP_FAIL: 'SIGNUP-FAIL',

  SIGN_IN_START: 'SIGN-IN-START',
  SIGN_IN_SUCCESS: 'SIGN-IN-SUCCESS',
  SIGN_IN_FAIL: 'SIGN-IN-FAIL',

  SIGN_OUT_START: 'SIGN-OUT-START',
  SIGN_OUT_SUCCESS: 'SIGN-OUT-SUCCESS',
  SIGN_OUT_FAIL: 'SIGN-OUT-FAIL',

  UPDATE_PASSWORD_START: 'UPDATE-PASSWORD-START',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE-PASSWORD-SUCCESS',
  UPDATE_PASSWORD_FAIL: 'UPDATE-PASSWORD-FAIL',

  GET_USER_DATA_START: 'GET-USER-DATA-START',
  GET_USER_DATA_SUCCESS: 'GET-USER-DATA-SUCCESS',
  GET_USER_DATA_FAIL: 'GET-USER-DATA-FAIL',

  UPDATE_USER_DATA_START: 'UPDATE-USER-DATA-START',
  UPDATE_USER_DATA_SUCCESS: 'UPDATE-USER-DATA-SUCCESS',
  UPDATE_USER_DATA_FAIL: 'UPDATE-USER-DATA-FAIL',

  GET_USERS_START: 'GET-USERS-START',
  GET_USERS_SUCCESS: 'GET-USERS-SUCCESS',
  GET_USERS_FAIL: 'GET-USERS-FAIL',

  OPEN_PROFILE_BAR: 'OPEN-PROFILE-BAR',
  CLOSE_PROFILE_BAR: 'CLOSE-PROFILE-BAR',

  GET_PROFILE_INFO_START: 'GET-PROFILE-INFO-START',
  GET_PROFILE_INFO_SUCCESS: 'GET-PROFILE-INFO-SUCCESS',
  GET_PROFILE_INFO_FAIL: 'GET-PROFILE-INFO-FAIL',

  OPEN_ADD_CONVERSATION_MODAL: 'OPEN-ADD-CONVERSATION-MODAL',
  CLOSE_ADD_CONVERSATION_MODAL: 'CLOSE-ADD-CONVERSATION-MODAL',

	GET_CONVERSATIONS_START: 'GET-CONVERSATIONS-START',
	GET_CONVERSATIONS_SUCCESS: 'GET-CONVERSATIONS-SUCCESS',
	GET_CONVERSATIONS_FAIL: 'GET-CONVERSATIONS-FAIL',

	SET_CONVERSATIONS_FILTER: 'SET-CONVERSATIONS-FILTER',

  CREATE_DIRECT_CONVERSATION_START: 'CREATE-DIRECT-CONVERSATION-START',
  CREATE_DIRECT_CONVERSATION_SUCCESS: 'CREATE-DIRECT-CONVERSATION-SUCCESS',
  CREATE_DIRECT_CONVERSATION_FAIL: 'CREATE-DIRECT-CONVERSATION-FAIL',

	REMOVE_CONVERSATION_START: 'REMOVE-CONVERSATION-START',
	REMOVE_CONVERSATION_SUCCESS: 'REMOVE-CONVERSATION-SUCCESS',
	REMOVE_CONVERSATION_FAIL: 'REMOVE-CONVERSATION-FAIL',

	CHOOSE_CONVERSATION: 'CHOOSE-CONVERSATION',

	SET_CONVERSATION_MESSAGE_START: 'SET-CONVERSATION-MESSAGE-START',
	SET_CONVERSATION_MESSAGE_SUCCESS: 'SET-CONVERSATION-MESSAGE-SUCCESS',
	SET_CONVERSATION_MESSAGE_FAIL: 'SET-CONVERSATION-MESSAGE-FAIL',

	GET_CONVERSATION_MESSAGES_START: 'GET-CONVERSATION-MESSAGES-START',
	GET_CONVERSATION_MESSAGES_SUCCESS: 'GET-CONVERSATION-MESSAGES-SUCCESS',
	GET_CONVERSATION_MESSAGES_FAIL: 'GET-CONVERSATION-MESSAGES-FAIL',

	REMOVE_CONVERSATION_MESSAGE_START: 'REMOVE-CONVERSATION-MESSAGE-START',
	REMOVE_CONVERSATION_MESSAGE_SUCCESS: 'REMOVE-CONVERSATION-MESSAGE-SUCCESS',
	REMOVE_CONVERSATION_MESSAGE_FAIL: 'REMOVE-CONVERSATION-MESSAGE-FAIL',

	SET_CONVERSATION_INPUT: 'SET-CONVERSATION-INPUT',
}
