export const actionTypes = {
  SIGNUP_START: 'SIGNUP-START',
  SIGNUP_SUCCESS: 'SIGNUP-SUCCESS',
  SIGNUP_FAIL: 'SIGNUP-FAIL',

  SIGNIN_START: 'SIGNIN-START',
  SIGNIN_SUCCESS: 'SIGNIN-SUCCESS',
  SIGNIN_FAIL: 'SIGNIN-FAIL',

  LOGOUT_START: 'LOGOUT-START',
  LOGOUT_SUCCESS: 'LOGOUT-SUCCESS',
  LOGOUT_FAIL: 'LOGOUT-FAIL'
}
