export const actionTypes = {
  SIGNUP_START: 'SIGNUP-START',
  SIGNUP_SUCCESS: 'SIGNUP-SUCCESS',
  SIGNUP_FAIL: 'SIGNUP-FAIL',

  SIGNIN_START: 'SIGNIN-START',
  SIGNIN_SUCCESS: 'SIGNIN-SUCCESS',
  SIGNIN_FAIL: 'SIGNIN-FAIL',

  SIGNOUT_START: 'SIGNOUT-START',
  SIGNOUT_SUCCESS: 'SIGNOUT-SUCCESS',
  SIGNOUT_FAIL: 'SIGNOUT-FAIL',

  GET_USER_DATA_START: 'GET-USER-DATA-START',
  GET_USER_DATA_SUCCESS: 'GET-USER-DATA-SUCCESS',
  GET_USER_DATA_FAIL: 'GET-USER-DATA-FAIL',

  SET_USER: 'SET-USER'
}
